name:                fgs-swepub
version:             0.1.0.0
github:              "githubuser/fgs-swepub"
license:             BSD3
author:              "Karl Pettersson"
maintainer:          "karl.pettersson@slu.se"
copyright:           "2021 SLU"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fgs-swepub#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- generic-lens
- lens
- text
- xml-conduit
- xml-hamlet

library:
  source-dirs: src

executables:
  fgs-swepub:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fgs-swepub
    - aeson
    - bytestring

tests:
  fgs-swepub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fgs-swepub
